name: Build and Run Vending Machine with Test File Input

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Compile the vending machine code
      run: g++ -o vendingmachine vendingmachine.cpp

    - name: Run vending machine with test input
      run: timeout 30s ./vendingmachine < test_input.txt || echo "Program timed out or exited with error"
